### ISSUE TITLE
NoMethodError  to_msgpack

### ISSUE THREAD

**Issue by fgranato** [splunk/fluent-plugin-kubernetes-metrics#47]
I've installed Fluentd v1.4.2 and ruby v2.5.3p105 and I get the following errors:

2019-04-29 19:11:20 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2019-04-29 19:11:20 +0000:Time" location="/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event.rb:61:in `write'" tag="kubesystem.pod.cpu.cfs.periods.total"
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event.rb:61:in `write'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event.rb:61:in `block in to_msgpack_stream'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event.rb:107:in `each'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event.rb:60:in `to_msgpack_stream'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:222:in `format_stream'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/compat/output.rb:314:in `emit'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:218:in `emit'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/compat/output.rb:344:in `handle_stream_simple'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:870:in `execute_chunking'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:793:in `emit_buffered'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event_router.rb:96:in `emit_stream'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/event_router.rb:87:in `emit'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:602:in `block in emit_cadvisor_metrics'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:575:in `each'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:575:in `emit_cadvisor_metrics'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:676:in `handle_cadvisor_response'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.0/lib/fluent/plugin/in_kubernetes_metrics.rb:634:in `scrape_cadvisor_metrics'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-04-29 19:11:20 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-29 19:11:20 +0000 [error]: #0 Failed to scrape metrics, error=, #<NoMethodError: undefined method `to_msgpack' for 2019-04-29 19:11:20 +0000:Tim

The fluentd configuration is:
  <source>
      @type kubernetes_metrics
      tag kubesystem.*
      interval 10s
      node_name "#{ENV['MY_NODE_NAME']}"
      kubelet_port 10250
      use_rest_client true
      use_rest_client_ssl true
    </source>

What is the problem? I need configure other?

Thank a lot

**Comment by chaitanyaphalak** [comment]
@fgranato have you figured out the configuration issue?

**Comment by chaitanyaphalak** [comment]
Closing due to inactivity. Please open an issue if you need further assistance.
