### ISSUE TITLE
Getting error=#<NoMethodError: undefined method `[]' only in one of the Kubernetes matrics pod

### ISSUE THREAD

**Issue by saif-cl0ud** [splunk/fluent-plugin-kubernetes-metrics#58]
**What happened**:

I am using "Splunk connect for kubernetes" and everything is working fine except one of the metrics pod throwing below error:

chown: /fluentd/etc/splunk/..data: Read-only file system
chown: /fluentd/etc/splunk/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_09_25_23_05_29.807988908/splunk_hec_token: Read-only file system
chown: /fluentd/etc/splunk/..2019_09_25_23_05_29.807988908: Read-only file system
chown: /fluentd/etc/splunk/..2019_09_25_23_05_29.807988908: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/splunk: Read-only file system
chown: /fluentd/etc/fluent.conf: Read-only file system
chown: /fluentd/etc/..2019_09_25_23_05_29.489835498/fluent.conf: Read-only file system
chown: /fluentd/etc/..2019_09_25_23_05_29.489835498: Read-only file system
chown: /fluentd/etc/..2019_09_25_23_05_29.489835498: Read-only file system
chown: /fluentd/etc/..data: Read-only file system
chown: /fluentd/etc: Read-only file system
chown: /fluentd/etc: Read-only file system
2019-09-25 23:05:35 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-09-25 23:05:37 +0000 [info]: Use URL https://10.225.204.58:10250/stats/summary for creating client to query kubelet summary api
2019-09-25 23:05:37 +0000 [info]: Use URL https://10.225.204.58:10250/stats/ for creating client to query kubelet stats api
2019-09-25 23:05:37 +0000 [info]: Use URL https://10.225.204.58:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-09-25 23:05:37 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type kubernetes_metrics
    tag "kube.*"
    node_name "pbpr-rno-np-k8w0.abc.com"
    use_rest_client_ssl true
    insecure_ssl true
    cluster_name cluster_name
    interval 15s
  </source>
  <filter kube.**>
    @type record_modifier
    <record>
      metric_name ${tag}
      cluster_name cluster_name
    </record>
  </filter>
  <filter kube.node.**>
    @type record_modifier
    <record>
      source ${record['node']}
    </record>
  </filter>
  <filter kube.pod.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}
    </record>
  </filter>
  <filter kube.sys-container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['name']}
    </record>
  </filter>
  <filter kube.container.**>
    @type record_modifier
    <record>
      source ${record['node']}/${record['pod-name']}/${record['container-name']}
    </record>
  </filter>
  <match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "pbpr-splunk.abc.com"
    hec_port 443
    hec_token "ea35wdwqdc9-a6f9-8wedqa997a24"
    host "pbpr-rno-np-k8w0.abc.com"
    index "kubernetes_metrics"
    source "${tag}"
    insecure_ssl true
    <buffer>
      @type "memory"
      chunk_limit_records 10000
      chunk_limit_size 100m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 3
      total_limit_size 400m
    </buffer>
  </match>
</ROOT>
2019-09-25 23:05:37 +0000 [info]: starting fluentd-1.4.0 pid=6 ruby="2.5.5"
2019-09-25 23:05:37 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2019-09-25 23:05:40 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.1'
2019-09-25 23:05:40 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-09-25 23:05:40 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.1.0'
2019-09-25 23:05:40 +0000 [info]: gem 'fluentd' version '1.4.0'
2019-09-25 23:05:40 +0000 [info]: adding filter pattern="kube.**" type="record_modifier"
2019-09-25 23:05:40 +0000 [info]: adding filter pattern="kube.node.**" type="record_modifier"
2019-09-25 23:05:40 +0000 [info]: adding filter pattern="kube.pod.**" type="record_modifier"
2019-09-25 23:05:40 +0000 [info]: adding filter pattern="kube.sys-container.**" type="record_modifier"
2019-09-25 23:05:40 +0000 [info]: adding filter pattern="kube.container.**" type="record_modifier"
2019-09-25 23:05:40 +0000 [info]: adding match pattern="kube.**" type="splunk_hec"
2019-09-25 23:05:41 +0000 [info]: adding source type="kubernetes_metrics"
2019-09-25 23:05:42 +0000 [info]: #0 Use URL https://10.225.204.58:10250/stats/summary for creating client to query kubelet summary api
2019-09-25 23:05:42 +0000 [info]: #0 Use URL https://10.225.204.58:10250/stats/ for creating client to query kubelet stats api
2019-09-25 23:05:42 +0000 [info]: #0 Use URL https://10.225.204.58:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2019-09-25 23:05:42 +0000 [warn]: parameter 'cluster_name' in <source>
  @type kubernetes_metrics
  tag "kube.*"
  node_name "pbpr-rno-np-k8w0.abc.com"
  use_rest_client_ssl true
  insecure_ssl true
  cluster_name cluster_name
  interval 15s
</source> is not used.
2019-09-25 23:05:42 +0000 [info]: #0 starting fluentd worker pid=16 ppid=6 worker=0
2019-09-25 23:05:42 +0000 [info]: #0 fluentd worker is now running worker=0
2019-09-25 23:05:58 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:327:in `emit_network_metrics'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:557:in `emit_pod_metrics'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:569:in `each'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:569:in `emit_metrics'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:651:in `handle_response'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes-metrics-1.1.1/lib/fluent/plugin/in_kubernetes_metrics.rb:612:in `scrape_metrics'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-09-25 23:05:58 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-09-25 23:06:13 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:06:13 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:06:28 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:06:28 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:06:43 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:06:43 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:06:58 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:06:58 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:07:13 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:07:13 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:07:28 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:07:28 +0000 [error]: #0 suppressed same stacktrace
2019-09-25 23:07:43 +0000 [error]: #0 Failed to scrape metrics, error=#<NoMethodError: undefined method `[]' for nil:NilClass>
  2019-09-25 23:07:43 +0000 [error]: #0 suppressed same stacktrace

**What you expected to happen**:

It should run correctly

**How to reproduce it (as minimally and precisely as possible)**:

This is specific to my environment .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T05:14:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"
- Ruby version (use `ruby --version`):
n/a (It's running inside the container)
- OS (e.g: `cat /etc/os-release`):
n/a (It's running inside the container)
- Splunk version:
Splunk Enterprise 7.3
- Others:

**Comment by chaitanyaphalak** [comment]
How are you installing this in kubernetes?
Are you using https://github.com/splunk/splunk-connect-for-kubernetes ?
Can you post the config?
What kubernetes version?
Is it self hosted?

**Comment by chaitanyaphalak** [comment]
Closing due to inacitivity.
